version: '3.8'

services:
  # Service for the MySQL database
  mysqldb:
    image: mysql:5.7 # Official MySQL image version 5.7
    restart: unless-stopped
    env_file: ./.env # File for environment variables
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}" # Port forwarding
    volumes:
      - db:/var/lib/mysql # Volume for data persistence
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Service for the Spring Boot application
  app:
    depends_on:
      - mysqldb # Wait for MySQL to be ready
    image: ouma96/backend-spring:1.0.0 # Ensure this image exists
    restart: on-failure
    env_file: ./.env # File for environment variables
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}" # Port forwarding for the Spring app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: {} # Volume for persisting MySQL data
